#see for java tunning https://docs.oracle.com/cd/E15523_01/web.1111/e13814/jvm_tuning.htm#PERFM161
version: '3.8'
services:
  #Docker Compose creates a virtual network between the services and the DNS name 
  #used for each service is its name: that’s why it’s possible to use eureka-discovery as the hostname.
  registry-discovery:
    container_name: id-eureka
    image: moviecatalogueparent/microservice-docker-eurekaserver:latest
    ports:
      - 8761:8761
    environment:
         - JAVA_OPTS=
         - Xms256M 
         - Xmx256M
  configuration:
    container_name: id-config
    image: moviecatalogueparent/microservice-docker-configserver:latest
    volumes:
      #this it use because we are using a local github repository /host/path:/container/path use ./ for relative path
      - ./config-server-repo:/tmp/config-server
      #All projets will have a variable value  DEUREKA_SERVER this tell where find a registry-discovery server
    environment:
         - JAVA_OPTS=
         - Xms256M 
         - Xmx256M
         - EUREKA_SERVER=http://registry-discovery:8761/eureka
         #-Dspring.cloud.config.server.native.searchLocations=/var/config-data
    depends_on:
      - registry-discovery
    ports:
      - 8085:8085
  administration:
    container_name: id-admin
    image: moviecatalogueparent/microservice-docker-adminserver:latest   
      #All projets will have a variable value  DEUREKA_SERVER this tell where find a registry-discovery server 
    environment:
         - JAVA_OPTS=
         - Xms256M 
         - Xmx256M
         - EUREKA_SERVER=http://registry-discovery:8761/eureka
         #-Dspring.cloud.config.server.native.searchLocations=/var/config-data
    depends_on:
      - registry-discovery
    ports:
      - 8084:8084
  movie-assessment:
    container_name: movie-assessment
    image: moviecatalogueparent/microservice-docker-movieassessment:latest
    environment:
         - JAVA_OPTS=
         - Xms256M 
         - Xmx256M
         - EUREKA_SERVER=http://registry-discovery:8761/eureka
         - Dspring.profiles.active=development
    depends_on:
      - registry-discovery
      - configuration
    ports:
      - 8081:8081
  movie-imdb:
    container_name: movie-imdb
    image: moviecatalogueparent/microservice-docker-moviedataimdb:latest
    environment:
         - JAVA_OPTS=
         - Xms256M 
         - Xmx256M
         - EUREKA_SERVER=http://registry-discovery:8761/eureka
         - Dspring.profiles.active=development
    depends_on:
      - registry-discovery
      - configuration
    ports:
      - 8082:8082
  postgres_db:
    container_name: postgres
    image: postgres:latest
    ports:
        - 3432:5432
    volumes:
        #allow *.sql, *.sql.gz, or *.sh and is execute only if data directory is empty
        - ./dbfiles:/docker-entrypoint-initdb.d
        - /var/lib/postgres_data:/var/lib/postgresql/data
    environment:
        #default postgres super user
        POSTGRES_USER: postgres
         #default passwor for postgres super user, it is only the required envvar for postgres image
        POSTGRES_PASSWORD: qwerty
        #main database if name is not specific thname of super user is use
        POSTGRES_DB: postgres  
        
  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "qwerty"
    ports:
      - 80:80
    depends_on:
      - postgres_db         
      
    